print('ola mundo !')
print('Two, three, four')
print('I dont wanna go to school tomorrow')
print('I cant study thinking about you')
print('And you know I always do')
print('I dont wanna go to sleep tonight')
print('When I can stay up thinking about you')
print('And you know I always do')
print("Marlboro nights")
print('You said you would, you said you would')
print('You said you would, you said you would')
print('Marlboro nights')
print('You said you would, you said you would')
print('You said you would, you said you would woo')
